add_newline = false

[line_break]
disabled = true

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 5_000
format = " took [$duration]($style) "

[directory]
truncation_length = 1
read_only = "🔒"
read_only_style= "bold white"

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '
style = "bold white"

[git_status]
conflicted = "🏳 "
ahead = "🏎️ 💨×${count} "
behind = "🐢×${count} "
diverged = "🔱 🏎️ 💨×${ahead_count} 🐢×${behind_count} "
untracked = "🤷×${count} "
stashed = "📦 "
modified = "📝×${count} "
staged = "🗃️×${count} "
renamed = "📛×${count} "
deleted = "🗑️×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold #ea00d9"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 50
style = "bold dimmed white"
disabled = false

[python]
format = "[$symbol$version]($style) "
style = "bold #f57800"
symbol = "🐍"
pyenv_version_name = true

[docker_context]
format = "via [🐋 $context](blue bold)"

[golang]
symbol = " "

[aws]
format = 'on [$symbol  $profile]($style) '
style = 'bold blue'
symbol = '🅰  ☁️'

[aws.profile_aliases]
dev = '🥷 dev'
