# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- walker --gapplication-service &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
exec-once = awww-daemon --format xrgb
exec-once = awww-daemon --format xrgb && awww img $HOME/Pictures/wallpapers/3-cat-blue-eye-mocha.png
