# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = launch-browser
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts


bindd = $mainMod, return, Terminal, exec, $terminal +new-window --working-directory="$(cmd-terminal-cwd)"
# bindd = $mainMod, G, Terminal, exec, $terminal --working-directory="$(current-cmd-cwd)" -e lazygit
bindd = $mainMod, T, File manager, exec, uwsm app -- nautilus --new-window
# bindd = $mainMod, W, Browser, exec, google-chrome-stable
bindd = $mainMod, W, Browser, exec, LIBVA_DRIVER_NAME=iHD LIBVA_DEVICE_NAME=/dev/dri/renderD129 brave
bind = $mainMod, E, exec, $scriptsDir/QuickEdit.sh
bind = $mainMod, D, exec, $scriptsDir/QuickEditDots.sh
bind = $mainMod, P, exec, $scriptsDir/QuickScreenThings.sh
bindd = $mainMod SHIFT, B, Browser (private), exec, $browser --private
bindd = $mainMod, B, Activity, exec, $terminal -e btop
bindd = $mainMod, G, Docker, exec, $terminal -e lazydocker

bind = $mainMod, Z, exec, hyprctl keyword cursor:zoom_factor $(awk "BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') + 0.5}") # Zoom out

bind = $mainMod, X, exec, hyprctl keyword cursor:zoom_factor $(awk "BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') - 0.5}") # Zoom in


source = ~/.config/hypr/bindings/tiling.conf
source = ~/.config/hypr/bindings/utilities.conf

