$mainMod = SUPER

# Menus
bindd = $mainMod, SPACE, Launch apps, exec, ~/.config/rofi/launchers/type-2/launcher.sh

# Aesthetics
bindd = $mainMod CTRL, SPACE, Change background, exec, change-bg
bindd = $mainMod, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle

# Notifications
bindd = $mainMod, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = $mainMod SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = $mainMod CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Toggle nightlight
bindd = $mainMod CTRL, N, Toggle nightlight, exec, toggle-nightlight

# Screenshots
bindd = , PRINT, Screenshot of region, exec, cmd-screenshot
bindd = SHIFT, PRINT, Screenshot of window, exec, cmd-screenshot window
bindd = CTRL, PRINT, Screenshot of display, exec, cmd-screenshot output

# Screen recordings
bindd = ALT, PRINT, Screen record a region, exec, cmd-screenrecord region
bindd = ALT SHIFT, PRINT, Screen record a region with audio, exec, cmd-screenrecord region audio
bindd = CTRL ALT, PRINT, Screen record display, exec, cmd-screenrecord output
bindd = CTRL ALT SHIFT, PRINT, Screen record display with audio, exec, cmd-screenrecord output audio

# Color picker
bindd = $mainMod, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

